--- 
data_items: []

tags: 
- fuel
- stationary
- combustion
- EPA
- US
- tires
- climate_leaders
- calculation
- direct
- emission_factor
- physical_properties
- EPA_mandatory
- EPA_mandatory_fuel
provenance: "[[http://www.epa.gov/stateply/resources/index.html|US EPA/Climate Leaders]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  mass: Mass of tires consumed
  energyPerMass: "Energy per mass of tires ('heating' or 'calorific' value) "
  energyConsumed: Quantity of energy consumed
  type: Type of fuel
  source: 
  massCO2PerEnergy: CO,,2,, emissions per unit of energy
wikiname: EPA_Stationary_combustion_of_tires
usages:
  byMass : {  energyConsumed : ignored }
  byEnergy : { mass : forbidden }
  order : [byMass, byEnergy ]
