--- 
data_items: []

tags: 
- home
- business
- energy
- electricity
- country
- calculation
- emission_factor
- direct
- global
- international
provenance: WBCSD 2006
gallery: 
show: "1"
authority: enterprise
ivds: 
  lastReading: Previous meter reading - this is used to derive an energy consumption estimate
  kWhReadingCurrent: 
  country: Country/region
  energyConsumption: Energy consumption estimate
  kWhPerMonth: 
  source: 
  kgCO2PerKWh: CO,,2,, emissions factor
  currentReading: Current meter reading - this is used to derive an energy consumption estimate
  kWhReadingLast: 
wikiname: Electricity
usages:
  byAbsoluteEnergyConsumption: { currentReading : forbidden, lastReading : forbidden }
  byMeterReadings: { energyConsumption : forbidden }
  order: [ byAbsoluteEnergyConsumption, byMeterReadings ]
