--- 
data_items: []

tags: 
- ethylene_oxide
- petrochemical
- IPCC
- IPCC_tier1
- IPCC_industry
- IPCC_industry_chemical
- EPA
- EPA_mandatory
- EPA_mandatory_petrochemical
- calculation
- emission_factor
- direct
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_3_Ch3_Chemical_Industry.pdf|IPCC-NGGIP]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  massCH4PerMass: Quantity of CH,,4,, emissions per unit produced
  massCO2PerMass: Quantity of CO,,2,, emissions per unit produced
  mass: Quantity of ethylene oxide produced
  catalystSelectivity: Value for catalyst selectivity
  massFeedstockPerMass: " Quantity of feedstock required per unit production"
  process: Type of process
  methaneFlared: Choose 'yes' or 'no' to specify flaring practice
  massFeedstock: Quantity of feedstock consumed
  source: 
wikiname: Ethylene_oxide_production
usages:
  byProduction: {  massFeedstock : ignored }
  byConsumption: { mass : forbidden }
  order: [ byProduction, byConsumption ]
