--- 
data_items: []

tags: 
- petrochemical
- vinyl_chloride_monomer
- IPCC
- IPCC_tier1
- IPCC_industry
- IPCC_industry_chemical
- EPA
- EPA_mandatory
- EPA_mandatory_petrochemical
- calculation
- emission_factor
- direct
- global
- EDC
- VCM
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/3_Volume3/V3_3_Ch3_Chemical_Industry.pdf|IPCC-NGGIP]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  massCH4PerMass: Quantity of CH,,4,, emissions per unit produced
  massCO2PerMass: Quantity of CO,,2,, emissions per unit produced
  mass: Quantity of vinyl chloride monomer produced
  massFeedstockPerMass: " Quantity of feedstock required per unit production"
  process: Type of process
  emission: Type of emission
  massFeedstock: Quantity of feedstock consumed
  source: 
wikiname: Vinyl_chloride_monomer_production
usages:
  byProduction: {  massFeedstock : ignored }
  byConsumption: { mass : forbidden }
  order: [ byProduction, byConsumption ]
