--- 
data_items: []

tags: 
- agriculture
- IPCC
- IPCC_agriculture
- IPCC_agriculture_soil
- IPCC_tier1
- soil
- fertilizer
- manure
- organic
- calculation
- direct
- emission_factor
- global
provenance: "[[http://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/4_Volume4/V4_11_Ch11_N2O&CO2.pdf|IPCC]]"
gallery: "nil"
show: "1"
authority: enterprise
ivds: 
  isLeached: Set to 'true' to specify that the soil expriences leaching. Otherwise leaching is assumed to be absent
  fractionLeached: Typical fraction of urine and dung-N which is leached
  fractionVolatilised: Typical fraction of urine and dung-N which is volatilised
  massPerMassLeached: Conversion factor for leached-N to N,,2,,O-N
  type: Type of livestock urine and dung
  massPerMass: Direct conversion factor for urine and dung-N to N,,2,,O-N
  massNAdded: Quantity of urine and dung-N applied to managed soil
  source: 
  massPerMassVolatilised: Conversion factor for volatilised-N to N,,2,,O-N
wikiname: Animal_associated_soil_N2O_emissions
name: "IPCC methodology for urine and dung deposition onto managed soils"
