--- 
data_items: []

tags: 
- transport
- passenger
- ship
- mobile
- distance
- calculation
- emission_factor
- direct
provenance: "[[http://www.defra.gov.uk/environment/business/reporting/conversion-factors.htm|DEFRA]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  country: Country in which travel taken
  numberOfPassengers: Number of passengers under consideration
  distancePerJourney: Distance travelled per journey
  isReturn: Set "true", if return journey
  type: Travel type
  distanceKmPerMonth: Distance travelled per month
  typicalJourneyDistance: Typical distance
  kgCO2PerPassengerKmIE: CO,,2,, emissions factor in Ireland
  kgCO2PerKmPassenger: CO,,2,, emissions factor
  useTypicalDistance: Set "true" to use typical distance
  journeyFrequency: Journey frequency
  numberOfJourneys: Number of journeys
  source: 
  distance: Distance travelled
wikiname: Generic_ship_transport
usages:
  byAbsoluteDistance: { country : optional, numberOfPassengers : optional, distancePerJourney : ignored, journeyFrequency : ignored, isReturn : ignored, numberOfJourneys : ignored, useTypicalDistance : ignored }
  byMultipleJourneys: { country : optional, numberOfPassengers : optional, distance : forbidden, isReturn : optional, useTypicalDistance : optional }
  order: [ byAbsoluteDistance, byMultipleJourneys ]
