--- 
data_items: []

tags: 
- ice
- construction
- materials
- calculation
- emission_factor
- energy
- lca
provenance: "[[http://people.bath.ac.uk/cj219/|Inventory of Carbon & Energy]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  material: Material 
  type: Specific type of material
  subtype: Subtype of material
  energyPerMass: Embodied energy per unit mass of material
  massCO2PerMass: Embodied CO,,2,, emissions per unit mass of material
  massCO2ePerMass: Embodied CO,,2,,e emissions per unit mass of material
  boundary: Life cycle analysis boundary, i.e. the stages in the material life cycle which are represented by the energy and CO,,2,, factors
  note: Author notes on the sourcing of data
  mass: Mass of material used
wikiname: ICE_v2_by_mass
name: "Inventory of Carbon & Energy methodology for materials by mass"
