--- 
data_items: []

tags: 
- fuel
- stationary
- combustion
- EPA
- US
- gas
- climate_leaders
- calculation
- direct
- emission_factor
- physical_properties
- EPA_mandatory
- EPA_mandatory_fuel
provenance: "[[http://www.epa.gov/stateply/resources/index.html|US EPA/Climate Leaders]]"
gallery: 
show: "1"
authority: enterprise
ivds: 
  energyPerVolume: "Energy per volume of gas ('heating' or 'calorific' value) "
  energyConsumed: Quantity of energy consumed
  volume: Volume of gas consumed
  subtype: Subtype of gas
  type: Type of gas
  burningContext: Context of burning (e.g. 'residential' 'electricity')
  massCO2PerEnergy: CO,,2,, emissions per unit of energy
  includeNonCO2Gases:
wikiname: EPA_Stationary_combustion_of_gas
usages:
  byVolume : { energyConsumed : ignored, includeNonCO2Gases : forbidden }
  byEnergy : { volume : forbidden, includeNonCO2Gases : forbidden }  
  order : [ byVolume, byEnergy ]
