--- 
data_items: []

provenance: "[[http://www.epa.gov/climatechange/emissions/archived/downloads/tsd/TSD%20wastewater_020409.pdf|EPA]]"
tags: 
- waste
- N2O
- denitrification
- nitrification
- water_treatment
- calculation
- direct
- US
- emission_factor
- business
- EPA
- EPA_mandatory
- EPA_mandatory_wastewater
authority: enterprise
show: "1"
gallery: 
ivds: 
  massN2OPerPersonWithout: N,,2,,O emissions per person //without// nitrification/denitrification
  industryFactor: Industrial/commercial adjustment factor
  massN2OPerPersonWith: N,,2,,O emissions per person //with// nitrification/denitrification
  type: Type of process
  totalPopulation: Total service population
  source: 
  populationWith: Population served by biological denitrification
wikiname: Waste_water_treatment_N2O
usages:
  default: { populationWith : optional, industryFactor : optional, massN2OPerPersonWith : optional, massN2OPerPersonWithout : optional }
